/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.sundydemo.learning1.java.database;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.ObjectTypeInfo;
import com.sundydemo.learning1.java.database.tables.BookInfo;
import com.sundydemo.learning1.java.database.tables.CourseContentTable;
import com.sundydemo.learning1.java.database.tables.CourseDetailsTable;
import com.sundydemo.learning1.java.database.tables.CoursePlatformTable;
import com.sundydemo.learning1.java.database.tables.CoursesCodelabDetailsTable;
import com.sundydemo.learning1.java.database.tables.CoursesDocTable;
import com.sundydemo.learning1.java.database.tables.CoursesMainCategoryTable;
import com.sundydemo.learning1.java.database.tables.CoursesPriceType;
import com.sundydemo.learning1.java.database.tables.CoursesSubCategoryTable;
import com.sundydemo.learning1.java.database.tables.CoursesTypeTable;
import com.sundydemo.learning1.java.database.tables.ExamTable;
import com.sundydemo.learning1.java.database.tables.FavPodcast;
import com.sundydemo.learning1.java.database.tables.FavouritePodcast;
import com.sundydemo.learning1.java.database.tables.MyCoursesTable;
import com.sundydemo.learning1.java.database.tables.QuestionsTable;
import com.sundydemo.learning1.java.database.tables.RecentlyViewedCoursesTable;
import com.sundydemo.learning1.java.database.tables.Test;
import com.sundydemo.learning1.java.database.tables.UserActivitiesTable;
import com.sundydemo.learning1.java.database.tables.UsersInfoTable;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Definition of ObjectType Helper.
 *
 * @since 2021-06-16
 */
public final class ObjectTypeInfoHelper {
    private static final int FORMAT_VERSION = 2;
    private static final int OBJECT_TYPE_VERSION = 19; //this number is cloud database version number which must be same as your cloud database version number. (you can check it on your AGC console board)

    public static ObjectTypeInfo getObjectTypeInfo() {
        ObjectTypeInfo objectTypeInfo = new ObjectTypeInfo();
        objectTypeInfo.setFormatVersion(FORMAT_VERSION);
        objectTypeInfo.setObjectTypeVersion(OBJECT_TYPE_VERSION);
        List<Class<? extends CloudDBZoneObject>> objectTypeList = new ArrayList<>();
        Collections.addAll(objectTypeList, CoursesPriceType.class, UserActivitiesTable.class, BookInfo.class, FavouritePodcast.class, CoursesDocTable.class,
            ExamTable.class, CourseDetailsTable.class, RecentlyViewedCoursesTable.class, CoursePlatformTable.class, CoursesMainCategoryTable.class,
            FavPodcast.class, CoursesCodelabDetailsTable.class, CoursesTypeTable.class, CourseContentTable.class, QuestionsTable.class,
            Test.class, CoursesSubCategoryTable.class, UsersInfoTable.class, MyCoursesTable.class);
        objectTypeInfo.setObjectTypes(objectTypeList);
        return objectTypeInfo;
    }
}
