/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.sundydemo.learning1.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType CoursesMainCategoryTable.
 *
 * @since 2021-06-16
 */
@PrimaryKeys({"courseMainCategoryId"})
public final class CoursesMainCategoryTable extends CloudDBZoneObject {
    private Integer courseMainCategoryId;

    private String courseMainCategoryName;

    public CoursesMainCategoryTable() {
        super(CoursesMainCategoryTable.class);
    }

    public void setCourseMainCategoryId(Integer courseMainCategoryId) {
        this.courseMainCategoryId = courseMainCategoryId;
    }

    public Integer getCourseMainCategoryId() {
        return courseMainCategoryId;
    }

    public void setCourseMainCategoryName(String courseMainCategoryName) {
        this.courseMainCategoryName = courseMainCategoryName;
    }

    public String getCourseMainCategoryName() {
        return courseMainCategoryName;
    }

}
