/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.sundydemo.learning1.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType CoursesDocTable.
 *
 * @since 2021-06-16
 */
@PrimaryKeys({"courseName"})
public final class CoursesDocTable extends CloudDBZoneObject {
    private String courseName;

    private String docTableOfContent;

    private String docDescription;

    private String docUrl;

    private String docCodeLabUrl;

    private String docPlatformsIds;

    public CoursesDocTable() {
        super(CoursesDocTable.class);
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setDocTableOfContent(String docTableOfContent) {
        this.docTableOfContent = docTableOfContent;
    }

    public String getDocTableOfContent() {
        return docTableOfContent;
    }

    public void setDocDescription(String docDescription) {
        this.docDescription = docDescription;
    }

    public String getDocDescription() {
        return docDescription;
    }

    public void setDocUrl(String docUrl) {
        this.docUrl = docUrl;
    }

    public String getDocUrl() {
        return docUrl;
    }

    public void setDocCodeLabUrl(String docCodeLabUrl) {
        this.docCodeLabUrl = docCodeLabUrl;
    }

    public String getDocCodeLabUrl() {
        return docCodeLabUrl;
    }

    public void setDocPlatformsIds(String docPlatformsIds) {
        this.docPlatformsIds = docPlatformsIds;
    }

    public String getDocPlatformsIds() {
        return docPlatformsIds;
    }

}
