/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.sundydemo.learning1.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType CoursesCodelabDetailsTable.
 *
 * @since 2021-06-16
 */
@PrimaryKeys({"codeLabId"})
public final class CoursesCodelabDetailsTable extends CloudDBZoneObject {
    private Integer codeLabId;

    private Integer courseId;

    private String codeLabUrl;

    private String codeLabContentA;

    private String codeLabContentB;

    private String codeLabContentC;

    private String codeLabContentD;

    private String codeLabContentE;

    private String codeLabContentF;

    private String codeLabContentG;

    private String codeLabContentH;

    private String codeLabContentI;

    @DefaultValue(stringValue = "true")
    private String codeLabContentJ;

    @DefaultValue(stringValue = "true")
    private String codeLabContentK;

    @DefaultValue(stringValue = "true")
    private String codeLabContentL;

    public CoursesCodelabDetailsTable() {
        super(CoursesCodelabDetailsTable.class);
        this.codeLabContentJ = "true";
        this.codeLabContentK = "true";
        this.codeLabContentL = "true";
    }

    public void setCodeLabId(Integer codeLabId) {
        this.codeLabId = codeLabId;
    }

    public Integer getCodeLabId() {
        return codeLabId;
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public Integer getCourseId() {
        return courseId;
    }

    public void setCodeLabUrl(String codeLabUrl) {
        this.codeLabUrl = codeLabUrl;
    }

    public String getCodeLabUrl() {
        return codeLabUrl;
    }

    public void setCodeLabContentA(String codeLabContentA) {
        this.codeLabContentA = codeLabContentA;
    }

    public String getCodeLabContentA() {
        return codeLabContentA;
    }

    public void setCodeLabContentB(String codeLabContentB) {
        this.codeLabContentB = codeLabContentB;
    }

    public String getCodeLabContentB() {
        return codeLabContentB;
    }

    public void setCodeLabContentC(String codeLabContentC) {
        this.codeLabContentC = codeLabContentC;
    }

    public String getCodeLabContentC() {
        return codeLabContentC;
    }

    public void setCodeLabContentD(String codeLabContentD) {
        this.codeLabContentD = codeLabContentD;
    }

    public String getCodeLabContentD() {
        return codeLabContentD;
    }

    public void setCodeLabContentE(String codeLabContentE) {
        this.codeLabContentE = codeLabContentE;
    }

    public String getCodeLabContentE() {
        return codeLabContentE;
    }

    public void setCodeLabContentF(String codeLabContentF) {
        this.codeLabContentF = codeLabContentF;
    }

    public String getCodeLabContentF() {
        return codeLabContentF;
    }

    public void setCodeLabContentG(String codeLabContentG) {
        this.codeLabContentG = codeLabContentG;
    }

    public String getCodeLabContentG() {
        return codeLabContentG;
    }

    public void setCodeLabContentH(String codeLabContentH) {
        this.codeLabContentH = codeLabContentH;
    }

    public String getCodeLabContentH() {
        return codeLabContentH;
    }

    public void setCodeLabContentI(String codeLabContentI) {
        this.codeLabContentI = codeLabContentI;
    }

    public String getCodeLabContentI() {
        return codeLabContentI;
    }

    public void setCodeLabContentJ(String codeLabContentJ) {
        this.codeLabContentJ = codeLabContentJ;
    }

    public String getCodeLabContentJ() {
        return codeLabContentJ;
    }

    public void setCodeLabContentK(String codeLabContentK) {
        this.codeLabContentK = codeLabContentK;
    }

    public String getCodeLabContentK() {
        return codeLabContentK;
    }

    public void setCodeLabContentL(String codeLabContentL) {
        this.codeLabContentL = codeLabContentL;
    }

    public String getCodeLabContentL() {
        return codeLabContentL;
    }

}
