/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
  * * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.sundydemo.learning1.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType CourseDetailsTable.
 *
 * @since 2021-06-16
 */
@PrimaryKeys({"courseId"})
public final class CourseDetailsTable extends CloudDBZoneObject {
    private Integer courseId;

    private Integer mainCategoryId;

    private Integer subCategoryId;

    private Integer courseTypeId;

    private Integer coursePriceId;

    private String courseDocId;

    private String courseNmae;

    private String courseDesc;

    private String courseImageUrl;

    private String courseVideoUrl;

    private String courseAudioUrl;

    private String courseAuthor;

    private String coursePlaformId;

    private Integer courseCodelabId;

    private Integer courseContentId;

    public CourseDetailsTable() {
        super(CourseDetailsTable.class);
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public Integer getCourseId() {
        return courseId;
    }

    public void setMainCategoryId(Integer mainCategoryId) {
        this.mainCategoryId = mainCategoryId;
    }

    public Integer getMainCategoryId() {
        return mainCategoryId;
    }

    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    public Integer getSubCategoryId() {
        return subCategoryId;
    }

    public void setCourseTypeId(Integer courseTypeId) {
        this.courseTypeId = courseTypeId;
    }

    public Integer getCourseTypeId() {
        return courseTypeId;
    }

    public void setCoursePriceId(Integer coursePriceId) {
        this.coursePriceId = coursePriceId;
    }

    public Integer getCoursePriceId() {
        return coursePriceId;
    }

    public void setCourseDocId(String courseDocId) {
        this.courseDocId = courseDocId;
    }

    public String getCourseDocId() {
        return courseDocId;
    }

    public void setCourseNmae(String courseNmae) {
        this.courseNmae = courseNmae;
    }

    public String getCourseNmae() {
        return courseNmae;
    }

    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc;
    }

    public String getCourseDesc() {
        return courseDesc;
    }

    public void setCourseImageUrl(String courseImageUrl) {
        this.courseImageUrl = courseImageUrl;
    }

    public String getCourseImageUrl() {
        return courseImageUrl;
    }

    public void setCourseVideoUrl(String courseVideoUrl) {
        this.courseVideoUrl = courseVideoUrl;
    }

    public String getCourseVideoUrl() {
        return courseVideoUrl;
    }

    public void setCourseAudioUrl(String courseAudioUrl) {
        this.courseAudioUrl = courseAudioUrl;
    }

    public String getCourseAudioUrl() {
        return courseAudioUrl;
    }

    public void setCourseAuthor(String courseAuthor) {
        this.courseAuthor = courseAuthor;
    }

    public String getCourseAuthor() {
        return courseAuthor;
    }

    public void setCoursePlaformId(String coursePlaformId) {
        this.coursePlaformId = coursePlaformId;
    }

    public String getCoursePlaformId() {
        return coursePlaformId;
    }

    public void setCourseCodelabId(Integer courseCodelabId) {
        this.courseCodelabId = courseCodelabId;
    }

    public Integer getCourseCodelabId() {
        return courseCodelabId;
    }

    public void setCourseContentId(Integer courseContentId) {
        this.courseContentId = courseContentId;
    }

    public Integer getCourseContentId() {
        return courseContentId;
    }

}
