/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.sundydemo.learning1.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType ExamTable.
 *
 * @since 2021-06-16
 */
@PrimaryKeys({"examId"})
public final class ExamTable extends CloudDBZoneObject {
    private Integer examId;

    private Integer courseId;

    private String examName;

    private String examDescription;

    private Integer examDuration;

    private Integer examNoOfQuestions;

    private Integer examTotalMarks;

    private Integer examPassMarks;

    private Integer examAttempts;

    public ExamTable() {
        super(ExamTable.class);
    }

    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    public Integer getExamId() {
        return examId;
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public Integer getCourseId() {
        return courseId;
    }

    public void setExamName(String examName) {
        this.examName = examName;
    }

    public String getExamName() {
        return examName;
    }

    public void setExamDescription(String examDescription) {
        this.examDescription = examDescription;
    }

    public String getExamDescription() {
        return examDescription;
    }

    public void setExamDuration(Integer examDuration) {
        this.examDuration = examDuration;
    }

    public Integer getExamDuration() {
        return examDuration;
    }

    public void setExamNoOfQuestions(Integer examNoOfQuestions) {
        this.examNoOfQuestions = examNoOfQuestions;
    }

    public Integer getExamNoOfQuestions() {
        return examNoOfQuestions;
    }

    public void setExamTotalMarks(Integer examTotalMarks) {
        this.examTotalMarks = examTotalMarks;
    }

    public Integer getExamTotalMarks() {
        return examTotalMarks;
    }

    public void setExamPassMarks(Integer examPassMarks) {
        this.examPassMarks = examPassMarks;
    }

    public Integer getExamPassMarks() {
        return examPassMarks;
    }

    public void setExamAttempts(Integer examAttempts) {
        this.examAttempts = examAttempts;
    }

    public Integer getExamAttempts() {
        return examAttempts;
    }

}
