/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.sundydemo.learning1.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType RecentlyViewedCoursesTable.
 *
 * @since 2021-06-16
 */
@PrimaryKeys({"recentlyViewedId"})
public final class RecentlyViewedCoursesTable extends CloudDBZoneObject {
    private Integer recentlyViewedId;

    private String courseId;

    private String userId;

    private String courseName;

    public RecentlyViewedCoursesTable() {
        super(RecentlyViewedCoursesTable.class);
    }

    public void setRecentlyViewedId(Integer recentlyViewedId) {
        this.recentlyViewedId = recentlyViewedId;
    }

    public Integer getRecentlyViewedId() {
        return recentlyViewedId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    public String getCourseId() {
        return courseId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserId() {
        return userId;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public String getCourseName() {
        return courseName;
    }

}
