/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.sundydemo.learning1.java.database.tables;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType UserActivitiesTable.
 *
 * @since 2021-06-16
 */
@PrimaryKeys({"userId"})
public final class UserActivitiesTable extends CloudDBZoneObject {
    private Long userId;

    private String viewedCourseIds;

    private String suggestedCourseIds;

    public UserActivitiesTable() {
        super(UserActivitiesTable.class);
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setViewedCourseIds(String viewedCourseIds) {
        this.viewedCourseIds = viewedCourseIds;
    }

    public String getViewedCourseIds() {
        return viewedCourseIds;
    }

    public void setSuggestedCourseIds(String suggestedCourseIds) {
        this.suggestedCourseIds = suggestedCourseIds;
    }

    public String getSuggestedCourseIds() {
        return suggestedCourseIds;
    }

}
